=== zbndm/ossinsight/api/params.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "QuerySchema",
  "type": "object",
  "properties": {
    "name": {
      "description": "Query name, default is generated base on the file path.",
      "type": "string"
    },
    "public": {
      "description": "Indicating if the query is public.",
      "type": "boolean",
      "default": false
    },
    "deprecated": {
      "description": "Indicating if the query is deprecated",
      "type": "boolean",
      "default": false
    },
    "description": {
      "description": "Query description for documentation.",
      "type": "string"
    },
    "cacheProvider": {
      "description": "Specify how to implement caching, NORMAL_TABLE are used by default.",
      "enum": ["NORMAL_TABLE", "CACHED_TABLE"]
    },
    "cacheHours": {
      "description": "Cache time in hours, -1 indicates that the query cache will not expire.",
      "type": "number"
    },
    "refreshQueue": {
      "description": "Specify which queue is used to execute prefetch job. The default is MAIN.",
      "type": "string"
    },
    "refreshCron": {
      "description": "The CRON expressions that control when the refresh cache task is executed.",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/ConditionalRefreshCrons"
        }
      ]
    },
    "refreshHours": {
      "description": "Refresh cache time in hours, -1 indicates not to refresh.",
      "oneOf": [
        {
          "type": "number"
        },
        {
          "$ref": "#/definitions/ConditionalHours"
        }
      ]
    },
    "onlyFromCache": {
      "description": "Only return data from the cache.",
      "type": "boolean"
    },
    "params": {
      "description": "Query params declaration.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Params"
      }
    },
    "resultSchema": {
      "description": "Result data schema for description.",
      "$ref": "https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema"
    }
  },
  "additionalProperties": false,
  "required": [
    "cacheHours",
    "params"
  ],
  "definitions": {
    "Params": {
      "type": "object",
      "properties": {
        "name": {
          "description": "URL Search param name for the query.",
          "type": "string"
        },
        "description": {
          "description": "Param description for documentation. If undefined, value in param-descriptions.json would be taken as default",
          "type": "string"
        },
        "type": {
          "description": "Define the parameter type.",
          "type": "string",
          "enum": ["array", "date-range", "collection", "employees"]
        },
        "column": {
          "description": "Define the parameter corresponding column name.",
          "type": "string"
        },
        "dateRangeTo": {
          "description": "Set in date-range should use that moment as `to` time.",
          "type": "string",
          "enum": ["now", "last-valid-datetime"],
          "default": "last-valid-datetime"
        },
        "replaces": {
          "description": "Define substring in the query sql template. Replacing uses `String.replaceAll`, please make sure the replacing substring is not substring of other texts.",
          "type": "string"
        },
        "template": {
          "description": "Replacing templates, mapped by search value",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "default": {
          "description": "Default input value.",
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            }
          ]
        },
        "enums": {
          "description": "Enums for prefetching and validating, default is no prefetching and validating.",
          "oneOf": [
            {
              "description": "Predefined query params name.",
              "type": "string"
            },
            {
              "description": "The allowed values and should be prefetched.",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "pattern": {
          "description": "Regular expression for validating parameter value.",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "replaces"
      ]
    },
    "ConditionalHours": {
      "type": "object",
      "properties": {
        "param": {
          "type": "string"
        },
        "on": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "type": "number"
            }
          }
        }
      },
      "required": ["param", "on"],
      "additionalProperties": false
    },
    "ConditionalRefreshCrons": {
      "type": "object",
      "properties": {
        "param": {
          "type": "string"
        },
        "on": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          }
        }
      },
      "required": ["param", "on"],
      "additionalProperties": false
    }
  }
}

=== zbndm/ossinsight/configs/queries/events-per-year/params.json
{
  "cacheHours": -1,
  "refreshCron": "0 0 1 1 *",
  "onlyFromCache": true,
  "params": [
    {
      "name": "repo",
      "replaces": "db_repos",
      "enums": "repo_subset"
    },
    {
      "name": "event",
      "replaces": "WatchEvent",
      "enums": "event"
    },
    {
      "name": "n",
      "replaces": "10",
      "enums": "n"
    },
    {
      "name": "year",
      "replaces": "2021"
    }
  ]
}

=== zbndm/ossinsight/api/queries/events-history/params.json
{
  "cacheHours": -1,
  "refreshCron": "@monthly",
  "onlyFromCache": true,
  "params": [
    {
      "name": "repo",
      "replaces": "db_repos",
      "enums": "repo_subset"
    },
    {
      "name": "event",
      "replaces": "WatchEvent",
      "enums": "event"
    },
    {
      "name": "n",
      "replaces": "10",
      "enums": ["10", "20", "50"]
    },
    {
      "name": "years",
      "replaces": "7",
      "enums": ["1", "2", "5", "10"]
    }
  ]
}

=== zbndm/ossinsight/api/queries/analyze-stars-history/params.json
{
  "public": true,
  "description": "Star history for repo",
  "cacheHours": 1,
  "params": [
    {
      "name": "repoId",
      "replaces": "41986369",
      "type": "array",
      "pattern": "^[1-9]\\d*$"
    }
  ],
  "resultSchema": {
    "type": "object",
    "properties": {
      "event_month": {
        "type": "string",
        "description": "Event month"
      },
      "repo_id": {
        "type": "number",
        "description": "GitHub Repo ID"
      },
      "total": {
        "type": "number",
        "description": "Total stars in the month"
      }
    },
    "required": ["event_month", "repo_id", "total"]
  }
}

=== zbndm/ossinsight/configs/queries/trending-repos/params.json
{
  "public": true,
  "description": "Repository trending alternative to https://github.com/trending",
  "cacheHours": -1,
  "refreshCron": {
    "param": "period",
    "on": {
      "past_24_hours": "@daily",
      "past_week": "@daily",
      "past_month": "@daily",
      "past_3_months": "@daily"
    }
  },
  "onlyFromCache": true,
  "params": [
    {
      "name": "period",
      "description": "Trending time period.",
      "replaces": "DATE_SUB(NOW(), INTERVAL 1 MONTH)",
      "default": "past_24_hours",
      "enums": [
       "past_24_hours", "past_week", "past_month", "past_3_months"
      ],
      "template": {
        "past_24_hours": "DATE_SUB(NOW(), INTERVAL 1 DAY)",
        "past_week": "DATE_SUB(NOW(), INTERVAL 1 WEEK)",
        "past_month": "DATE_SUB(NOW(), INTERVAL 1 MONTH)",
        "past_3_months": "DATE_SUB(NOW(), INTERVAL 3 MONTH)"
      }
    },
    {
      "name": "language",
      "description": "Primary language",
      "replaces": "AND primary_language = 'Java'",
      "default": "All",
      "enums": [
        "All", "JavaScript", "Java", "Python", "PHP", "C++", "C#", "TypeScript", "Shell", "C", "Ruby", "Rust", "Go", "Kotlin", "HCL", "PowerShell", "CMake", "Groovy", "PLpgSQL", "TSQL", "Dart", "Swift", "HTML", "CSS", "Elixir", "Haskell", "Solidity", "Assembly", "R", "Scala", "Julia", "Lua", "Clojure", "Erlang", "Common Lisp", "Emacs Lisp", "OCaml", "MATLAB", "Objective-C", "Perl", "Fortran"
      ],
      "template": {
        "All": "",
        "JavaScript": "AND primary_language = 'JavaScript'",
        "Java": "AND primary_language = 'Java'",
        "Python": "AND primary_language = 'Python'",
        "PHP": "AND primary_language = 'PHP'",
        "C++": "AND primary_language = 'C++'",
        "C#": "AND primary_language = 'C#'",
        "TypeScript": "AND primary_language = 'TypeScript'",
        "Shell": "AND primary_language = 'Shell'",
        "C": "AND primary_language = 'C'",
        "Ruby": "AND primary_language = 'Ruby'",
        "Rust": "AND primary_language = 'Rust'",
        "Go": "AND primary_language = 'Go'",
        "Kotlin": "AND primary_language = 'Kotlin'",
        "HCL": "AND primary_language = 'HCL'",
        "PowerShell": "AND primary_language = 'PowerShell'",
        "CMake": "AND primary_language = 'CMake'",
        "Groovy": "AND primary_language = 'Groovy'",
        "PLpgSQL": "AND primary_language = 'PLpgSQL'",
        "TSQL": "AND primary_language = 'TSQL'",
        "Dart": "AND primary_language = 'Dart'",
        "Swift": "AND primary_language = 'Swift'",
        "HTML": "AND primary_language = 'HTML'",
        "CSS": "AND primary_language = 'CSS'",
        "Elixir": "AND primary_language = 'Elixir'",
        "Haskell": "AND primary_language = 'Haskell'",
        "Solidity": "AND primary_language = 'Solidity'",
        "Assembly": "AND primary_language = 'Assembly'",
        "R": "AND primary_language = 'R'",
        "Scala": "AND primary_language = 'Scala'",
        "Julia": "AND primary_language = 'Julia'",
        "Lua": "AND primary_language = 'Lua'",
        "Clojure": "AND primary_language = 'Clojure'",
        "Erlang": "AND primary_language = 'Erlang'",
        "Common Lisp": "AND primary_language = 'Common Lisp'",
        "Emacs Lisp": "AND primary_language = 'Emacs Lisp'",
        "OCaml": "AND primary_language = 'OCaml'",
        "MATLAB": "AND primary_language = 'MATLAB'",
        "Objective-C": "AND primary_language = 'Objective-C'",
        "Perl": "AND primary_language = 'Perl'",
        "Fortran": "AND primary_language = 'Fortran'"
      }
    }
  ],
  "resultSchema": {
    "type": "object",
    "properties": {
      "repo_id": {
        "type": "number"
      },
      "repo_name": {
        "type": "string"
      },
      "language": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "stars": {
        "type": "number"
      },
      "forks": {
        "type": "number"
      },
      "pull_requests": {
        "type": "number"
      },
      "pushes": {
        "type": "number"
      },
      "total_score": {
        "type": "number"
      },
      "contributor_logins": {
        "type": "string",
        "nullable": true
      },
      "collection_names": {
        "type": "string",
        "nullable": true
      }
    },
    "required": ["repo_id", "repo_name", "language", "description", "stars", "forks", "pull_requests", "pushes", "total_score", "contributor_logins", "collection_names"]
  }
}
